// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZPcM8s2xs-TRAKZt1GuUeyq-cU_aucg',
    appId: '1:152868044389:web:1326bc2e6dcea55390d08c',
    messagingSenderId: '152868044389',
    projectId: 'flutter-application-delivery',
    authDomain: 'flutter-application-delivery.firebaseapp.com',
    storageBucket: 'flutter-application-delivery.firebasestorage.app',
    measurementId: 'G-F4V5SCFHPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANMCMqMDtL-RNjyf0GzFmmREy-9EefUlw',
    appId: '1:152868044389:android:78d428d13cc50fb690d08c',
    messagingSenderId: '152868044389',
    projectId: 'flutter-application-delivery',
    storageBucket: 'flutter-application-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3WQjCRWFflAvKFCMgGA-FES8GAKW4R0',
    appId: '1:152868044389:ios:999367c1bee6d43890d08c',
    messagingSenderId: '152868044389',
    projectId: 'flutter-application-delivery',
    storageBucket: 'flutter-application-delivery.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationDelivery',
  );

}